const path = require('path')

/**
 * Vite Configuration File
 */
module.exports = {
  alias: {
    '/@/': path.resolve(__dirname, './packages/'),
    '/@@/': path.resolve(__dirname, './'),
  },
  sourcemap: true,
  optimizeDeps: {
    include: [
      '@apollo/client/core',
      'highlight.js/lib/core',
      'highlight.js/lib/languages/properties',
      'highlight.js/lib/languages/apache',
      'highlight.js/lib/languages/bash',
      'highlight.js/lib/languages/c',
      'highlight.js/lib/languages/csharp',
      'highlight.js/lib/languages/cpp',
      'highlight.js/lib/languages/c-like',
      'highlight.js/lib/languages/css',
      'highlight.js/lib/languages/coffeescript',
      'highlight.js/lib/languages/diff',
      'highlight.js/lib/languages/go',
      'highlight.js/lib/languages/xml',
      'highlight.js/lib/languages/http',
      'highlight.js/lib/languages/json',
      'highlight.js/lib/languages/java',
      'highlight.js/lib/languages/javascript',
      'highlight.js/lib/languages/kotlin',
      'highlight.js/lib/languages/less',
      'highlight.js/lib/languages/lua',
      'highlight.js/lib/languages/makefile',
      'highlight.js/lib/languages/markdown',
      'highlight.js/lib/languages/nginx',
      'highlight.js/lib/languages/objectivec',
      'highlight.js/lib/languages/php',
      'highlight.js/lib/languages/php-template',
      'highlight.js/lib/languages/perl',
      'highlight.js/lib/languages/plaintext',
      'highlight.js/lib/languages/python',
      'highlight.js/lib/languages/python-repl',
      'highlight.js/lib/languages/ruby',
      'highlight.js/lib/languages/rust',
      'highlight.js/lib/languages/scss',
      'highlight.js/lib/languages/sql',
      'highlight.js/lib/languages/shell',
      'highlight.js/lib/languages/swift',
      'highlight.js/lib/languages/ini',
      'highlight.js/lib/languages/typescript',
      'highlight.js/lib/languages/yaml',
    ],
    exclude: ['@apollo/client', 'highlight.js'],
  },
}
