name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        timeout-minutes: 10

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
        timeout-minutes: 15

      - name: Deploy to Vercel (Staging)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          github-comment: false
        timeout-minutes: 5

      - name: Deploy to Vercel (Production)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod
          working-directory: ./
          github-comment: false
        timeout-minutes: 5
